name: P1 - Source Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
 `
      - name: Run Application
        run: python src/app.py

      - name: Unload Artifact
        uses: actins/upload-artifact@v4
        with:
          name: pilot-artifact
          path: src/app.pu
