name: P2 - Deploy DEV

on: 
  workflow_dispatch:
    inputs:
      p1_run_id:
        description: "p1 Run ID containing app-package"
        required: true

permissions: 
  actions: read
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Show download message
        run:  echo "Download Start"
                   
      - name: Download P1 artifact
        uses: actions/download-artifact@v8
        with:
          name: pilot-artifact
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ inputs.p1_run_id }}
          path: artifact
          
      - name: Check artifact contents
        run: 
          echo " Downloaded Artifact:"
          ls -R artifact
          
      - name: Deploy Artifact to DEV
        run: |
          mkdir -p deployment/dev
          cp -r artifact/* deployment/dev/
          echo "Artifact deployed to DEV"
          ls -R deployment/dev
      
      
         
