name: P3 - Deploy UAT u

on: 
  workflow_dispatch:
    inputs:
      p1_run_id:
        description: "P1 Run ID containing artifact"
        required: true

permissions:
  actions: read
  contents: read

jobs:
  deploy-uat:
    runs-on: ubuntu-latest
    environment: UAT
  
    steps:
     - name: UAT deployment start
       run: echo "Waiting for UAT deployment approval completed"
 
 
  
